/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_by5388_jni_Windows */

#ifndef _Included_com_by5388_jni_Windows
#define _Included_com_by5388_jni_Windows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_by5388_jni_Windows
 * Method:    showWindow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_by5388_jni_Windows_showWindow
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
